bash run_quant_13b.sh --input_model=/home/azure-node-inc/llama-2-13-hf-onnx --output_model=/home/azure-node-inc/llama-2-13-hf-onnx-inc-sq --smooth_quant=True --alpha=0.5 --tokenizer=/home/azure-node-inc/llama-2-13-hf-onnx --quant_format="QOperator" --workspace=./sq-workspace
bash run_benchmark.sh --input_model=/home/azure-node-inc/llama-2-13-hf-onnx-inc-sq --mode=accuracy --tokenizer=/home/azure-node-inc/llama-2-13-hf-onnx --tasks=lambada_openai --workspace=./sq-workspace
bash run_quant_13b.sh --input_model=/home/azure-node-inc/llama-2-13-hf-onnx --output_model=/home/azure-node-inc/llama-2-13-hf-onnx-inc-sq --smooth_quant=True --alpha=0.55 --tokenizer=/home/azure-node-inc/llama-2-13-hf-onnx --quant_format="QOperator" --workspace=./sq-workspace
bash run_benchmark.sh --input_model=/home/azure-node-inc/llama-2-13-hf-onnx-inc-sq --mode=accuracy --tokenizer=/home/azure-node-inc/llama-2-13-hf-onnx --tasks=lambada_openai --workspace=./sq-workspace
bash run_quant_13b.sh --input_model=/home/azure-node-inc/llama-2-13-hf-onnx --output_model=/home/azure-node-inc/llama-2-13-hf-onnx-inc-sq --smooth_quant=True --alpha=0.6 --tokenizer=/home/azure-node-inc/llama-2-13-hf-onnx --quant_format="QOperator" --workspace=./sq-workspace
bash run_benchmark.sh --input_model=/home/azure-node-inc/llama-2-13-hf-onnx-inc-sq --mode=accuracy --tokenizer=/home/azure-node-inc/llama-2-13-hf-onnx --tasks=lambada_openai --workspace=./sq-workspace
bash run_quant_13b.sh --input_model=/home/azure-node-inc/llama-2-13-hf-onnx --output_model=/home/azure-node-inc/llama-2-13-hf-onnx-inc-sq --smooth_quant=True --alpha=0.65 --tokenizer=/home/azure-node-inc/llama-2-13-hf-onnx --quant_format="QOperator" --workspace=./sq-workspace
bash run_benchmark.sh --input_model=/home/azure-node-inc/llama-2-13-hf-onnx-inc-sq --mode=accuracy --tokenizer=/home/azure-node-inc/llama-2-13-hf-onnx --tasks=lambada_openai --workspace=./sq-workspace
bash run_quant_13b.sh --input_model=/home/azure-node-inc/llama-2-13-hf-onnx --output_model=/home/azure-node-inc/llama-2-13-hf-onnx-inc-sq --smooth_quant=True --alpha=0.7 --tokenizer=/home/azure-node-inc/llama-2-13-hf-onnx --quant_format="QOperator" --workspace=./sq-workspace
bash run_benchmark.sh --input_model=/home/azure-node-inc/llama-2-13-hf-onnx-inc-sq --mode=accuracy --tokenizer=/home/azure-node-inc/llama-2-13-hf-onnx --tasks=lambada_openai --workspace=./sq-workspace
bash run_quant_13b.sh --input_model=/home/azure-node-inc/llama-2-13-hf-onnx --output_model=/home/azure-node-inc/llama-2-13-hf-onnx-inc-sq --smooth_quant=True --alpha=0.75 --tokenizer=/home/azure-node-inc/llama-2-13-hf-onnx --quant_format="QOperator" --workspace=./sq-workspace
bash run_benchmark.sh --input_model=/home/azure-node-inc/llama-2-13-hf-onnx-inc-sq --mode=accuracy --tokenizer=/home/azure-node-inc/llama-2-13-hf-onnx --tasks=lambada_openai --workspace=./sq-workspace
bash run_quant_13b.sh --input_model=/home/azure-node-inc/llama-2-13-hf-onnx --output_model=/home/azure-node-inc/llama-2-13-hf-onnx-inc-sq --smooth_quant=True --alpha=0.8 --tokenizer=/home/azure-node-inc/llama-2-13-hf-onnx --quant_format="QOperator" --workspace=./sq-workspace
bash run_benchmark.sh --input_model=/home/azure-node-inc/llama-2-13-hf-onnx-inc-sq --mode=accuracy --tokenizer=/home/azure-node-inc/llama-2-13-hf-onnx --tasks=lambada_openai --workspace=./sq-workspace
bash run_quant_13b.sh --input_model=/home/azure-node-inc/llama-2-13-hf-onnx --output_model=/home/azure-node-inc/llama-2-13-hf-onnx-inc-sq --smooth_quant=True --alpha=0.85 --tokenizer=/home/azure-node-inc/llama-2-13-hf-onnx --quant_format="QOperator" --workspace=./sq-workspace
bash run_benchmark.sh --input_model=/home/azure-node-inc/llama-2-13-hf-onnx-inc-sq --mode=accuracy --tokenizer=/home/azure-node-inc/llama-2-13-hf-onnx --tasks=lambada_openai --workspace=./sq-workspace
bash run_quant_13b.sh --input_model=/home/azure-node-inc/llama-2-13-hf-onnx --output_model=/home/azure-node-inc/llama-2-13-hf-onnx-inc-sq --smooth_quant=True --alpha=0.9 --tokenizer=/home/azure-node-inc/llama-2-13-hf-onnx --quant_format="QOperator" --workspace=./sq-workspace
bash run_benchmark.sh --input_model=/home/azure-node-inc/llama-2-13-hf-onnx-inc-sq --mode=accuracy --tokenizer=/home/azure-node-inc/llama-2-13-hf-onnx --tasks=lambada_openai --workspace=./sq-workspace
bash run_quant_13b.sh --input_model=/home/azure-node-inc/llama-2-13-hf-onnx --output_model=/home/azure-node-inc/llama-2-13-hf-onnx-inc-sq --smooth_quant=True --alpha=0.95 --tokenizer=/home/azure-node-inc/llama-2-13-hf-onnx --quant_format="QOperator" --workspace=./sq-workspace
bash run_benchmark.sh --input_model=/home/azure-node-inc/llama-2-13-hf-onnx-inc-sq --mode=accuracy --tokenizer=/home/azure-node-inc/llama-2-13-hf-onnx --tasks=lambada_openai --workspace=./sq-workspace
